(function(g){var window=this;var $Ca=function(a,b){return g.Wb(a,b)},i6=function(a){g.Tm(a,"zx",g.xb());
return a},j6=function(a,b,c){g.za(c)||(c=[String(c)]);
g.Wm(a.o,b,c)},aDa=function(a,b){var c=[];
g.Fk(b,function(a){try{var b=g.uD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.tD(b)&&c.push(a):c.push(a)},a);
return c},bDa=function(a,b){var c=aDa(a,b);
(0,g.C)(c,function(a){g.uD.prototype.remove.call(this,a)},a)},cDa=function(a){if(a.Fd){if(a.Fd.locationOverrideToken)return{locationOverrideToken:a.Fd.locationOverrideToken};
if(null!=a.Fd.latitudeE7&&null!=a.Fd.longitudeE7)return{latitudeE7:a.Fd.latitudeE7,longitudeE7:a.Fd.longitudeE7}}return null},dDa=function(a,b,c,d){var e=new g.Km(null,void 0);
a&&g.Lm(e,a);b&&g.Mm(e,b);c&&g.Nm(e,c);d&&g.Om(e,d);return e},eDa=function(a){g.jG[a]&&(a=g.jG[a],(0,g.C)(a,function(a){g.hG[a]&&delete g.hG[a]}),a.length=0)},fDa=function(a){var b=g.gG();
if(b)if(b.clear(a),a)eDa(a);else for(var c in g.jG)eDa(c)},k6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Em;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",gDa(this,a.capabilities||""),hDa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},gDa=function(a,b){a.capabilities.clear();
(0,g.Ud)(b.split(","),g.Fa($Ca,iDa)).forEach(function(b){a.capabilities.add(b)})},hDa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},l6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},m6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},jDa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},kDa=function(a){return new l6(a)},lDa=function(a){return g.za(a)?(0,g.I)(a,kDa):[]},n6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},o6=function(a){return g.za(a)?"["+(0,g.I)(a,n6).join(",")+"]":"null"},p6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},mDa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},q6=function(a,b){return g.Ka(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},r6=function(a,b){return g.Ka(a,function(a){return m6(a,b)})},nDa=function(){var a=(0,g.hH)();
a&&bDa(a,a.o.Zd(!0))},s6=function(){var a=g.kH("yt-remote-connected-devices")||[];
g.fb(a);return a},oDa=function(a){if(g.Pa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},pDa=function(a){g.jH("yt-remote-connected-devices",a,86400)},u6=function(){if(t6)return t6;
var a=g.kH("yt-remote-device-id");a||(a=p6(),g.jH("yt-remote-device-id",a,31536E3));for(var b=s6(),c=1,d=a;g.Oa(b,d);)c++,d=a+"#"+c;return t6=d},v6=function(){var a=s6(),b=u6();
g.Oa(a,b);g.mH()&&g.ib(a,b);a=oDa(a);if(g.Pa(a))try{g.SG("remote_sid")}catch(c){}else try{g.RG("remote_sid",a.join(","),-1)}catch(c){}},qDa=function(){return g.kH("yt-remote-session-browser-channel")},rDa=function(){return g.kH("yt-remote-local-screens")||[]},sDa=function(){g.jH("yt-remote-lounge-token-expiration",!0,86400)},tDa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(rDa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.sm)(c,function(a){return!g.Oa(b,a)})&&sDa();
g.jH("yt-remote-local-screens",a,31536E3)},uDa=function(a,b){g.jH("yt-remote-session-browser-channel",a);
g.jH("yt-remote-session-screen-id",b);var c=s6(),d=u6();g.Oa(c,d)||c.push(d);pDa(c);v6()},w6=function(a){a||(g.lH("yt-remote-session-screen-id"),g.lH("yt-remote-session-video-id"));
v6();a=s6();g.Ta(a,u6());pDa(a)},vDa=function(){if(!x6){var a=g.FD();
a&&(x6=new g.oD(a))}return x6?!!x6.get("yt-remote-use-staging-server"):!1},wDa=function(){var a=window.document.createElement("a");
g.id(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Bb(a)},xDa=function(a,b){var c=g.Nd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.jd(c,g.le("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},yDa=function(){var a=wDa(),b=window.document.getElementById(a),c=b&&g.rF(b,"loaded");
c||b&&!c||(b=xDa(a,function(){g.rF(b,"loaded")||(g.qF(b,"loaded","true"),g.nG(a),g.nE(g.Fa(fDa,a),0))}))},y6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},zDa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},z6=function(a){a.length?ADa(a.shift(),function(){z6(a)}):A6()},BDa=function(a){return"chrome-extension://"+a+B6},ADa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},C6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},A6=function(){var a=zDa();
a&&a(!1,"No cast extension found")},D6=function(){if(CDa){var a=2,b=zDa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;ADa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",A6,c)}},DDa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(D6(),a({command:"cast.sender.init"}))},EDa=function(){D6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);z6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+B6,"//www.gstatic.com/eureka/clank"+B6])},E6=function(a,b,c){g.M.call(this);
this.F=null!=c?(0,g.A)(a,c):a;this.yd=b;this.D=(0,g.A)(this.TK,this);this.o=!1;this.A=0;this.B=this.Da=null;this.C=[]},F6=function(){},G6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.$m(this);this.A=new g.Cg;this.A.setInterval(250)},GDa=function(a,b,c){a.dk=1;
a.Ah=i6(b.clone());a.ij=c;a.D=!0;FDa(a,null)},H6=function(a,b,c,d,e){a.dk=1;
a.Ah=i6(b.clone());a.ij=null;a.D=c;e&&(a.cF=!1);FDa(a,d)},FDa=function(a,b){a.Rk=(0,g.H)();
I6(a);a.bi=a.Ah.clone();j6(a.bi,"t",a.F);a.wn=0;a.Qc=a.o.Is(a.o.kn()?b:null);0<a.Ct&&(a.tq=new g.ll((0,g.A)(a.sG,a,a.Qc),a.Ct));a.Y.W(a.Qc,"readystatechange",a.jW);var c=a.Hi?g.dc(a.Hi):{};a.ij?(a.mr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Qc.send(a.bi,a.mr,a.ij,c)):(a.mr="GET",a.cF&&!g.Jd&&(c.Connection="close"),a.Qc.send(a.bi,a.mr,null,c));a.o.Df(1)},JDa=function(a,b,c){for(var d=!0;!a.si&&a.wn<c.length;){var e=HDa(a,c);
if(e==J6){4==b&&(a.Bh=4,K6(15),d=!1);break}else if(e==IDa){a.Bh=4;K6(16);d=!1;break}else L6(a,e)}4==b&&0==c.length&&(a.Bh=1,K6(17),d=!1);a.Kf=a.Kf&&d;d||(M6(a),N6(a))},HDa=function(a,b){var c=a.wn,d=b.indexOf("\n",c);
if(-1==d)return J6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return IDa;d+=1;if(d+c>b.length)return J6;var e=b.substr(d,c);a.wn=d+c;return e},LDa=function(a,b){a.Rk=(0,g.H)();
I6(a);var c=b?window.location.hostname:"";a.bi=a.Ah.clone();g.Tm(a.bi,"DOMAIN",c);g.Tm(a.bi,"t",a.F);try{a.Lf=new window.ActiveXObject("htmlfile")}catch(n){M6(a);a.Bh=7;K6(22);N6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in O6)k=O6[l];else if(l in KDa)k=O6[l]=KDa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=O6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.kd(g.Bc("b/12014412"),d+"</body></html>");a.Lf.open();a.Lf.write(g.bd(c));a.Lf.close();a.Lf.parentWindow.m=(0,g.A)(a.rV,a);a.Lf.parentWindow.d=(0,g.A)(a.kE,a,!0);a.Lf.parentWindow.rpcClose=(0,g.A)(a.kE,a,!1);c=a.Lf.createElement("DIV");a.Lf.parentWindow.document.body.appendChild(c);d=g.Pc(a.bi.toString());d=g.rb(g.Mc(d));d=g.kd(g.Bc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.hd(c,g.bd(d));a.o.Df(1)},
I6=function(a){a.gx=(0,g.H)()+a.C;
MDa(a,a.C)},MDa=function(a,b){if(null!=a.ll)throw Error("WatchDog timer not null");
a.ll=P6((0,g.A)(a.IV,a),b)},Q6=function(a){a.ll&&(g.x.clearTimeout(a.ll),a.ll=null)},N6=function(a){a.o.pA()||a.si||a.o.bq(a)},M6=function(a){Q6(a);
g.lf(a.tq);a.tq=null;a.A.stop();g.fn(a.Y);if(a.Qc){var b=a.Qc;a.Qc=null;b.abort();b.dispose()}a.Lf&&(a.Lf=null)},L6=function(a,b){try{a.o.cE(a,b),a.o.Df(4)}catch(c){}},ODa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;NDa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){ODa(a,b,c,d,f)},f)})}},NDa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{R6(d),c(!0)}catch(e){}};
d.onerror=function(){try{R6(d),c(!1)}catch(e){}};
d.onabort=function(){try{R6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{R6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},R6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},PDa=function(a){this.o=a;
this.A=new F6},QDa=function(a){var b=S6(a.o,a.wl,"/mail/images/cleardot.gif");
i6(b);ODa(b.toString(),5E3,(0,g.A)(a.YJ,a),3,2E3);a.Df(1)},U6=function(a){var b=a.o.I;
if(null!=b)K6(5),b?(K6(11),T6(a.o,a,!1)):(K6(12),T6(a.o,a,!0));else if(a.Ce=new G6(a,void 0,void 0,void 0),a.Ce.Hi=a.At,b=a.o,b=S6(b,b.kn()?a.Zl:null,a.Bt),K6(5),!g.Hd||g.tc(10))j6(b,"TYPE","xmlhttp"),H6(a.Ce,b,!1,a.Zl,!1);else{j6(b,"TYPE","html");var c=a.Ce;a=!!a.Zl;c.dk=3;c.Ah=i6(b.clone());LDa(c,a)}},V6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new F6;this.H=a||null;this.I=null!=b?b:null;this.F=c||!1},RDa=function(a,b){this.o=a;
this.map=b;this.context=null},SDa=function(a){g.nf.call(this,"statevent",a)},TDa=function(a,b){g.nf.call(this,"timingevent",a);
this.size=b},UDa=function(a){g.nf.call(this,"serverreachability",a)},XDa=function(a){VDa(a);
if(3==a.o){var b=a.Sm++,c=a.Jo.clone();g.Tm(c,"SID",a.B);g.Tm(c,"RID",b);g.Tm(c,"TYPE","terminate");W6(a,c);b=new G6(a,a.B,b,void 0);b.dk=2;b.Ah=i6(c.clone());(new window.Image).src=b.Ah;b.Rk=(0,g.H)();I6(b)}WDa(a)},YDa=function(a){a.uK(1,0);
a.Jo=S6(a,null,a.zt);X6(a)},VDa=function(a){a.nh&&(a.nh.abort(),a.nh=null);
a.xc&&(a.xc.cancel(),a.xc=null);a.yg&&(g.x.clearTimeout(a.yg),a.yg=null);Y6(a);a.ee&&(a.ee.cancel(),a.ee=null);a.sh&&(g.x.clearTimeout(a.sh),a.sh=null)},ZDa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new RDa(a.fR++,b));2!=a.o&&3!=a.o||X6(a)},X6=function(a){a.ee||a.sh||(a.sh=P6((0,g.A)(a.iE,a),0),a.Sj=0)},aEa=function(a,b){if(1==a.o){if(!b){a.Sm=Math.floor(1E5*Math.random());
var c=a.Sm++,d=new G6(a,"",c,void 0);d.Hi=null;var e=Z6(a),f=a.Jo.clone();g.Tm(f,"RID",c);g.Tm(f,"CVER","1");W6(a,f);GDa(d,f,e);a.ee=d;a.o=2}}else 3==a.o&&(b?$Da(a,b):0==a.A.length||a.ee||$Da(a))},$Da=function(a,b){if(b)if(6<a.wi){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.Sm-1;var d=Z6(a)}else c=b.G,d=b.ij;else c=a.Sm++,d=Z6(a);var e=a.Jo.clone();g.Tm(e,"SID",a.B);g.Tm(e,"RID",c);g.Tm(e,"AID",a.sk);W6(a,e);c=new G6(a,a.B,c,a.Sj+1);c.Hi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ee=c;GDa(c,e,d)},W6=function(a,b){if(a.xd){var c=a.xd.Vz();
c&&g.Jb(c,function(a,c){g.Tm(b,c,a)})}},Z6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.wi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.wi?e:f-d;try{g.Jb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},bEa=function(a){a.xc||a.yg||(a.G=1,a.yg=P6((0,g.A)(a.hE,a),0),a.Fj=0)},$6=function(a){if(a.xc||a.yg||3<=a.Fj)return!1;
a.G++;a.yg=P6((0,g.A)(a.hE,a),cEa(a,a.Fj));a.Fj++;return!0},T6=function(a,b,c){a.kr=c;
a.Yf=b.Kg;a.F||YDa(a)},Y6=function(a){null!=a.xi&&(g.x.clearTimeout(a.xi),a.xi=null)},cEa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.xd&&(c=null);var d=(0,g.A)(a.bX,a);c||(c=new g.Km("//www.google.com/images/cleardot.gif"),i6(c));NDa(c.toString(),1E4,d)}else K6(2);dEa(a,b)},dEa=function(a,b){a.o=0;
a.xd&&a.xd.Vy(b);WDa(a);VDa(a)},WDa=function(a){a.o=0;
a.Yf=-1;if(a.xd)if(0==a.C.length&&0==a.A.length)a.xd.us();else{g.Xa(a.C);var b=g.Xa(a.A);a.C.length=0;a.A.length=0;a.xd.us(b)}},S6=function(a,b,c){var d=g.Um(c);
if(""!=d.A)b&&g.Mm(d,b+"."+d.A),g.Nm(d,d.D);else{var e=window.location;d=dDa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Jl&&g.Jb(a.Jl,function(a,b){g.Tm(d,b,a)});
g.Tm(d,"VER",a.wi);W6(a,d);return d},P6=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},K6=function(a){b7.dispatchEvent(new SDa(b7,a))},eEa=function(){},fEa=function(a,b){this.action=a;
this.params=b||{}},c7=function(a,b){g.M.call(this);
this.o=new g.pu(this.iV,0,this);g.N(this,this.o);this.yd=5E3;this.A=0;if(g.Ba(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},d7=function(a,b,c){this.L=a;
this.F=b;this.B=new g.nD;this.A=new c7(this.LX,this);this.o=this.ib=null;this.K=!1;this.D=null;this.I="";this.H=this.C=0;this.G=[];this.M=c||!1},gEa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.kr,sessionId:a.o.B,arrayId:a.o.sk}},hEa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&aEa(a.o),XDa(a.o));a.H=0},e7=function(a){return!!a.o&&3==a.o.o},iEa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},f7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Sg(a)||"";b&&(this.port=":"+b);this.domain=g.Rg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ab(a,"10.0")&&(this.A=!1))},g7=function(a,b){var c=a.o;
if(g.u(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.ah(c+b,{})},h7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Fa(a.C,d,!0),onError:g.Fa(a.B,e),Cd:g.Fa(a.D,e)};c&&(a.Pb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.EE(b,a)},mEa=function(){var a=jEa;
kEa();i7.push(a);lEa(i7)},j7=function(a,b){kEa();
var c=i7,d=nEa(a,String(b));g.Pa(c)?oEa(d):(lEa(c),(0,g.C)(c,function(a){a(d)}))},kEa=function(){i7||(i7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",i7,void 0))},oEa=function(a){var b=(k7+1)%50;
k7=b;l7[b]=a;m7||(m7=49==b)},lEa=function(a){var b=l7;
if(b[0]){var c=k7,d=m7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
l7=Array(50);k7=-1;m7=!1}},nEa=function(a,b){var c=((0,g.H)()-pEa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},n7=function(a){g.ZF.call(this);
this.G=a;this.o=[]},qEa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},rEa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Ud)(a.o,function(a){return!!q6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=qEa(a,b[d])||c;return c},sEa=function(a,b){var c=a.o.length;
a.o=(0,g.Ud)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},o7=function(a,b,c,d){g.ZF.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Da=window.NaN},q7=function(a){n7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;p7(this);this.info("Initializing with "+o6(this.o))},tEa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=g7(a.B,"/pairing/get_lounge_token_batch");
h7(a.B,c,{screen_ids:b.join(",")},(0,g.A)(a.gL,a),(0,g.A)(a.fL,a))}},p7=function(a){var b=lDa(rDa());
b=(0,g.Ud)(b,function(a){return!a.uuid});
return rEa(a,b)},r7=function(a,b){tDa((0,g.I)(a.o,jDa));
b&&sDa()},t7=function(a,b){g.ZF.call(this);
this.F=b;var c=g.kH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Oa(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;s7("Initialized with "+g.Jg(this.o))},uEa=function(a,b,c){var d=g7(a.D,"/pairing/get_screen_availability");
h7(a.D,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},u7=function(a,b){a:if(g.Ob(b)!=g.Ob(a.o))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(s7("Updated online screens: "+g.Jg(a.o)),a.o=b,a.V("screenChange"));vEa(a)},v7=function(a){(0,window.isNaN)(a.B)||g.pE(a.B);
a.B=g.nE((0,g.A)(a.mw,a),0<a.C&&a.C<(0,g.H)()?2E4:1E4)},s7=function(a){j7("OnlineScreenService",a)},wEa=function(a){var b={};
(0,g.C)(a.F(),function(a){a.token?b[a.token]=a.id:this.gc("Requesting availability of screen w/o lounge token.")});
return b},vEa=function(a){a=g.Rb(g.Lb(a.o,function(a){return a}));
g.fb(a);a.length?g.jH("yt-remote-online-screen-ids",a.join(","),60):g.lH("yt-remote-online-screen-ids")},w7=function(a){n7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};xEa(this)},zEa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.ue();if(k=(c?r6(k,c):null)||r6(k,b)){k.uuid=b;var l=x7(a,k);uEa(a.A,l,function(a){e(a?l:null)})}else c?yEa(a,c,(0,g.A)(function(a){var f=x7(this,new l6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));uEa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},AEa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},yEa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Pb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.EE(g7(a.F,"/pairing/get_lounge_token_batch"),e)},BEa=function(a){a.o=a.B.ue();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+o6(a.o))},xEa=function(a){y7(a);
a.B=new q7(a.F);a.B.subscribe("screenChange",(0,g.A)(a.uL,a));BEa(a);a.C=lDa(g.kH("yt-remote-automatic-screen-cache")||[]);y7(a);a.info("Initializing automatic screens: "+o6(a.C));a.A=new t7(a.F,(0,g.A)(a.ue,a,!0));a.A.subscribe("screenChange",(0,g.A)(function(){this.V("onlineScreenChange")},a))},x7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=r6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.jH("yt-remote-automatic-screen-cache",(0,g.I)(a.C,jDa)));y7(a);a.D[b.uuid]=b.id;g.jH("yt-remote-device-id-map",a.D,31536E3);return b},y7=function(a){a.D=g.kH("yt-remote-device-id-map")||{}},z7=function(a,b,c){g.ZF.call(this);
this.M=c;this.I=a;this.A=b;this.B=null},A7=function(a,b){j7(a.M,b)},B7=function(a,b){z7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.A)(this.RX,this);this.D=(0,g.A)(this.UV,this);this.C=g.nE((0,g.A)(function(){CEa(this,null)},this),12E4)},DEa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Jg(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.z,(0,g.A)(function(){A7(this,"Failed to send message: getMdxSessionStatus.")},a)):A7(a,"Sending yt message without session: "+g.Jg(b))},CEa=function(a,b){g.pE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.A)(a.cq,a),d=(0,g.A)(a.Be,a);a.fA(b,c,d,5)}}else a.Be(Error("Waiting for session status timed out."))},C7=function(a,b,c){z7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.z;this.F=window.NaN;this.L=(0,g.A)(this.UX,this);this.o=g.z},EEa=function(a){a.o=a.I.zG(a.K,a.A.label,a.A.friendlyName,(0,g.A)(function(a){this.o=g.z;
this.cq(a)},a),(0,g.A)(function(a){this.o=g.z;
this.Be(a)},a))},FEa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}vDa()&&(b.env_useStageMdx=1);return g.Zg(b)},D7=function(a,b){z7.call(this,a,b,"ManualSession");
this.o=g.nE((0,g.A)(this.uk,this,null),150)},E7=function(a,b,c,d){g.ZF.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.A)(this.vU,this)},GEa=function(a,b){return b?g.Ka(a.B,function(a){return m6(b,a.label)},a):null},F7=function(a){j7("Controller",a)},jEa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},G7=function(a){return a.D||!!a.B.length||!!a.o},H7=function(a,b,c){b!=a.o&&(g.lf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.A)(a.fE,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.uk(null)):a.V("yt-remote-cast2-session-change",null))},HEa=function(a){var b=a.A.yG(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&m6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=GEa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},NEa=function(a,b,c,d,e,f,k){IEa()?JEa(b,e,f,k)&&(J7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?KEa(a,c):(window.__onGCastApiAvailable=function(b,d){b?KEa(a,c):(K7("Failed to load cast API: "+d),L7(!1),J7(!1),g.lH("yt-remote-cast-available"),g.lH("yt-remote-cast-receiver"),LEa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):yDa():C6("CriOS")?DDa():C6("Android")&&C6("Chrome/")&&window.navigator.presentation?EDa():window.chrome&&window.navigator.presentation&&!C6("Edge")?(D6(),z6(MEa.map(BDa))):A6())):I7("Cannot initialize because not running Chrome")},LEa=function(){I7("dispose");
var a=M7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);OEa(!1);g.lG(N7);N7.length=0},O7=function(){return!!g.kH("yt-remote-cast-installed")},PEa=function(){var a=g.kH("yt-remote-cast-receiver");
return a?a.friendlyName:null},QEa=function(){I7("clearCurrentReceiver");
g.lH("yt-remote-cast-receiver")},REa=function(){return O7()?M7()?M7().getCastSession():(K7("getCastSelector: Cast is not initialized."),null):(K7("getCastSelector: Cast API is not installed!"),null)},Q7=function(){O7()?M7()?P7()?(I7("Requesting cast selector."),M7().requestSession()):(I7("Wait for cast API to be ready to request the session."),N7.push(g.kG("yt-remote-cast2-api-ready",Q7))):K7("requestCastSelector: Cast is not initialized."):K7("requestCastSelector: Cast API is not installed!")},R7=
function(a,b){P7()?M7().setConnectedScreenStatus(a,b):K7("setConnectedScreenStatus called before ready.")},IEa=function(){var a=0<=g.Hb.search(/ (CrMo|Chrome|CriOS)\//);
return g.AI||a},SEa=function(a,b){M7().init(a,b)},JEa=function(a,b,c,d){var e=!1;
M7()||(a=new E7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.jH("yt-remote-cast-available",a);g.oG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){I7("onReceiverSelected: "+a.friendlyName);
g.jH("yt-remote-cast-receiver",a);g.oG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){I7("onReceiverResumed: "+a.friendlyName);
g.jH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){I7("onSessionChange: "+n6(a));
a||g.lH("yt-remote-cast-receiver");g.oG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
I7("cloudview.createSingleton_: "+e);return e},M7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},KEa=function(a,b){L7(!0);
J7(!1);SEa(a,function(a){a?(OEa(!0),g.nG("yt-remote-cast2-api-ready")):(K7("Failed to initialize cast API."),L7(!1),g.lH("yt-remote-cast-available"),g.lH("yt-remote-cast-receiver"),LEa());b(a)})},I7=function(a){j7("cloudview",a)},K7=function(a){j7("cloudview",a)},L7=function(a){I7("setCastInstalled_ "+a);
g.jH("yt-remote-cast-installed",a)},P7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},OEa=function(a){I7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},S7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.o=-1;this.muted=!1;this.audioTrackId=null;this.G=this.H=0;this.A=null;this.hasNext=this.dg=!1;this.K=this.I=this.B=this.D=0;this.C=window.NaN;this.F=!1;this.reset(a)},T7=function(a){a.audioTrackId=null;
a.A=null;a.o=-1;a.dg=!1;a.hasNext=!1;a.H=0;a.G=(0,g.H)();a.D=0;a.B=0;a.I=0;a.K=0;a.C=window.NaN;a.F=!1},U7=function(a){return a.rb()?((0,g.H)()-a.G)/1E3:0},V7=function(a,b){a.H=b;
a.G=(0,g.H)()},W7=function(a){switch(a.o){case 1:case 1081:return((0,g.H)()-a.G)/1E3+a.H;
case -1E3:return 0}return a.H},X7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T7(a)},Y7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.o;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ec(a.A);b.hasPrevious=a.dg;b.hasNext=a.hasNext;b.playerTime=a.H;b.playerTimeAt=a.G;b.seekableStart=a.D;b.seekableEnd=a.B;b.duration=a.I;b.loadedTime=a.K;b.liveIngestionTime=a.C;return b},$7=function(a,b){g.ZF.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.DC;this.B=this.A=null;this.I=(0,g.A)(this.PR,this);this.G=(0,g.A)(this.Vm,this);this.H=(0,g.A)(this.OR,this);this.K=(0,g.A)(this.bS,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.ox,this),TEa(this))):c=3;0!=c&&(b?this.ox(c):g.nE((0,g.A)(function(){this.ox(c)},this),0));
var d=REa();d&&Z7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},a8=function(a){return new S7(a.C.getPlayerContextData())},TEa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Fa(this.qU,a),this))},a)},UEa=function(a){(0,g.C)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},b8=function(a,b){50>a.D.yc()&&g.FC(a.D,b)},d8=function(a,b,c){var d=a8(a);
V7(d,c);-1E3!=d.o&&(d.o=b);c8(a,d)},e8=function(a,b,c){a.C.sendMessage(b,c)},c8=function(a,b){UEa(a);
a.C.setPlayerContextData(Y7(b));TEa(a)},Z7=function(a,b){a.B&&(a.B.removeUpdateListener(a.I),a.B.removeMediaListener(a.G),a.Vm(null));
a.B=b;a.B&&(j7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.I),a.B.addMediaListener(a.G),a.B.media.length&&a.Vm(a.B.media[0]))},VEa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=a8(a);b.contentId!=d.videoId&&j7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.o=c.playerState;V7(d,a.A.getEstimatedTime());c8(a,d)}else j7("CP","No cast media video. Ignoring state update.")},f8=function(a,b,c){return(0,g.A)(function(a){this.gc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.gc("Retrying "+b+" using MDx browser channel."),e8(this,b,c))},a)},g8=function(a,b,c){g.ZF.call(this);
this.D=window.NaN;this.O=!1;this.K=this.I=this.L=this.M=window.NaN;this.T=[];this.C=this.G=this.B=this.jb=this.o=null;this.pa=a;this.T.push(g.IF(window,"beforeunload",(0,g.A)(this.XK,this)));this.A=[];this.jb=new S7;this.aa=b.id;this.o=WEa(this,c);this.o.subscribe("handlerOpened",this.TR,this);this.o.subscribe("handlerClosed",this.QR,this);this.o.subscribe("handlerError",this.RR,this);this.o.subscribe("handlerMessage",this.SR,this);iEa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.jb.videoId;g.mH()&&g.jH("yt-remote-session-video-id",a)},this)},h8=function(a){j7("conn",a)},WEa=function(a,b){return new d7(g7(a.pa,"/bc"),b)},i8=function(a,b){a.V("proxyStateChange",b)},XEa=function(a){a.D=g.nE((0,g.A)(function(){h8("Connecting timeout");
this.F(1)},a),2E4)},j8=function(a){g.pE(a.D);
a.D=window.NaN},k8=function(a){g.pE(a.M);
a.M=window.NaN},YEa=function(a){l8(a);
a.L=g.nE((0,g.A)(function(){m8(this,"getNowPlaying")},a),2E4)},l8=function(a){g.pE(a.L);
a.L=window.NaN},$Ea=function(a,b){b&&(j8(a),k8(a));
b==(e7(a.o)&&(0,window.isNaN)(a.D))?b&&(i8(a,1),m8(a,"getSubtitlesTrack")):b?(a.Z()&&a.jb.reset(),i8(a,1),m8(a,"getNowPlaying"),ZEa(a)):a.F(1)},aFa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.jb.videoId&&(g.Zb(b.params)?a.jb.A=null:a.jb.A=b.params,a.V("remotePlayerChange"))},bFa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.jb.listId=b.params.listId||a.jb.listId;X7(a.jb,c,d);a.V("remoteQueueChange")},dFa=function(a,b){b.params=b.params||{};
bFa(a,b);cFa(a,b);a.V("autoplayDismissed")},cFa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
V7(a.jb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.jb.o&&(c=-1E3);a.jb.o=c;c=Number(b.params.loadedTime);a.jb.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.jb.I=(0,window.isNaN)(c)?0:c;c=a.jb;var d=Number(b.params.liveIngestionTime);c.C=d;c.F=(0,window.isNaN)(d)?!1:!0;c=a.jb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.D=(0,window.isNaN)(d)?0:d;c.B=(0,window.isNaN)(e)?0:e;1==a.jb.o?YEa(a):l8(a);
a.V("remotePlayerChange")},eFa=function(a,b){if(-1E3!=a.jb.o){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.jb.o=c;c=(0,window.parseInt)(b.params.currentTime,10);V7(a.jb,(0,window.isNaN)(c)?0:c);a.V("remotePlayerChange")}},fFa=function(a,b){var c="true"==b.params.muted;
a.jb.volume=(0,window.parseInt)(b.params.volume,10);a.jb.muted=c;a.V("remotePlayerChange")},gFa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},hFa=function(a,b){var c="true"==b.params.hasNext;
a.jb.dg="true"==b.params.hasPrevious;a.jb.hasNext=c;a.V("previousNextChange")},ZEa=function(a){g.pE(a.K);
a.K=g.nE((0,g.A)(a.F,a,1),864E5)},m8=function(a,b,c){c?h8("Sending: action="+b+", params="+g.Jg(c)):h8("Sending: action="+b);
a.o.sendMessage(b,c)},n8=function(a){n7.call(this,"ScreenServiceProxy");
this.fd=a;this.A=[];this.A.push(this.fd.$_s("screenChange",(0,g.A)(this.PX,this)));this.A.push(this.fd.$_s("onlineScreenChange",(0,g.A)(this.OT,this)))},mFa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.hE("MDX_CONFIG")||b;nDa();v6();o8||(o8=new f7(b?b.loungeApiHost:void 0),vDa()&&(o8.o="/api/loungedev"));p8||(p8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",p8,void 0));iFa();var c=q8();if(!c){var d=new w7(o8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=q8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);NEa(a,d,function(a){a?r8()&&R7(r8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.oG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),s8("Initializing: "+g.Jg(b)),t8.push(g.kG("yt-remote-cast2-availability-change",function(){g.oG("yt-remote-receiver-availability-change")})),t8.push(g.kG("yt-remote-cast2-receiver-selected",function(){u8(null);
g.oG("yt-remote-auto-connect","cast-selector-receiver")})),t8.push(g.kG("yt-remote-cast2-receiver-resumed",function(){g.oG("yt-remote-receiver-resumed","cast-selector-receiver")})),t8.push(g.kG("yt-remote-cast2-session-change",jFa)),t8.push(g.kG("yt-remote-connection-change",function(a){a?R7(r8(),"YouTube TV"):v8()||(R7(null,null),QEa())})),a=w8(),b.isAuto&&(a.id+="#dial"),g.eG("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),s8(" -- with channel params: "+
g.Jg(a)),kFa(a),c.start(),r8()||lFa())},oFa=function(){var a=nFa();
O7()&&g.kH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},nFa=function(){var a=q8().fd.$_gos();
var b=x8();b&&y8()&&(q6(a,b)||a.push(b));return mDa(a)},z8=function(){var a=pFa();
!a&&O7()&&PEa()&&(a={key:"cast-selector-receiver",name:PEa()});return a},pFa=function(){var a=nFa(),b=x8();
b||(b=v8());return g.Ka(a,function(a){return b&&m6(b,a.key)?!0:!1})},x8=function(){var a=r8();
if(!a)return null;var b=q8().ue();return r6(b,a)},jFa=function(a){s8("remote.onCastSessionChange_: "+n6(a));
if(a){var b=x8();b&&b.id==a.id?R7(b.id,"YouTube TV"):(b&&A8(),B8(a,1))}else y8()&&A8()},A8=function(){P7()?M7().stopSession():K7("stopSession called before API ready.");
var a=y8();a&&(a.disconnect(1),C8(null))},D8=function(){var a=y8();
return!!a&&3!=a.getProxyState()},s8=function(a){j7("remote",a)},q8=function(){if(!E8){var a=g.y("yt.mdx.remote.screenService_");
E8=a?new n8(a):null}return E8},r8=function(){return g.y("yt.mdx.remote.currentScreenId_")},qFa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},rFa=function(){return g.y("yt.mdx.remote.connectData_")},u8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},y8=function(){return g.y("yt.mdx.remote.connection_")},C8=function(a){var b=y8();
u8(null);a||qFa("");g.ua("yt.mdx.remote.connection_",a,void 0);p8&&((0,g.C)(p8,function(b){b(a)}),p8.length=0);
b&&!a?g.oG("yt-remote-connection-change",!1):!b&&a&&g.oG("yt-remote-connection-change",!0)},v8=function(){var a=g.mH();
if(!a)return null;var b=q8().ue();return r6(b,a)},B8=function(a,b){x8()&&x8();
qFa(a.id);var c=new g8(o8,a,w8());c.connect(b,rFa());c.subscribe("beforeDisconnect",function(a){g.oG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){y8()&&C8(null)});
C8(c)},lFa=function(){var a=v8();
a?(s8("Resume connection to: "+n6(a)),B8(a,0)):(w6(),QEa(),s8("Skipping connecting because no session screen found."))},iFa=function(){var a=w8();
if(g.Zb(a)){a=u6();var b=g.kH("yt-remote-session-name")||"",c=g.kH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},w8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},kFa=function(a){a?(g.jH("yt-remote-session-app",a.app),g.jH("yt-remote-session-name",a.name)):(g.lH("yt-remote-session-app"),g.lH("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},F8=function(a,b,c){g.M.call(this);
this.H=a;this.A=b;this.B=new g.WF(this);g.N(this,this.B);this.B.R(b,"onCaptionsTrackListChanged",this.iT);this.B.R(b,"captionschanged",this.NR);this.B.R(b,"captionssettingschanged",this.LF);this.B.R(b,"videoplayerreset",this.eq);this.B.R(b,"mdxautoplaycancel",this.XJ);this.T=this.B.R(b,"onVolumeChange",this.MD);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.bE,this);c.subscribe("remotePlayerChange",this.Ym,this);c.subscribe("remoteQueueChange",this.eq,this);c.subscribe("autoplayUpNext",this.xD,
this);c.subscribe("previousNextChange",this.YD,this);c.subscribe("nowAutoplaying",this.PD,this);c.subscribe("autoplayDismissed",this.wD,this);this.suggestion=null;this.I=new g.ZP(64);this.C=new g.pu(this.HF,500,this);g.N(this,this.C);this.D=new g.pu(this.IF,1E3,this);g.N(this,this.D);this.L=new E6(this.qX,0,this);g.N(this,this.L);this.F={};this.M=new g.pu(this.hG,1E3,this);g.N(this,this.M);this.K=new g.ll(this.TP,1E3,this);g.N(this,this.K);this.O=g.z;this.LF();this.eq();this.Ym()},G8=function(a,b){var c=
a.H,d=a.A.getVideoData().lengthSeconds;
c.I=b||0;c.o.V("progresssync",b,d)},sFa=function(a){G8(a,0);
a.C.stop();H8(a,new g.ZP(64))},J8=function(a,b){if(I8(a)&&!a.G){var c=null;
b&&(c={style:a.A.bj()},g.gc(c,b));a.o.wF(a.A.getVideoData(1).videoId,c);a.F=a8(a.o).A}},K8=function(a,b){var c=a.A.lg();
if(c){var d=c.se();var e=c.listId.toString()}var f=a.A.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.mk;f=cDa(f);var n=a8(c);l=l||0;var p={videoId:k,currentIndex:l};X7(n,k,l);g.u(b)&&(V7(n,b),p.currentTime=b);g.u(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Jg(f));e8(c,"setPlaylist",p);e||c8(c,n);H8(a,new g.ZP(1))},tFa=function(a,b){if(b){var c=a.A.Bc("captions","tracklist",{ZA:1});
c&&c.length?(a.A.Rd("captions","track",b),a.G=!1):(a.A.Bk("captions"),a.G=!0)}else a.A.Rd("captions","track",{})},I8=function(a){return a8(a.o).videoId==a.A.getVideoData(1).videoId},H8=function(a,b){a.D.stop();
var c=a.I;if(!g.dQ(c,b)){var d=g.X(b,2);d!=g.X(a.I,2)&&g.fU(a.A,d);a.I=b;uFa(a.H,c,b)}},L8=function(a){g.W.call(this,{J:"div",
N:"ytp-remote",P:[{J:"div",N:"ytp-remote-display-status",P:[{J:"div",N:"ytp-remote-display-status-icon",P:[g.Iqa()]},{J:"div",N:"ytp-remote-display-status-text",ca:"{{statustext}}"}]}]});this.B=new g.fV(this,250);g.N(this,this.B);this.C=a;this.R(a,"presentingplayerstatechange",this.D);vFa(this,g.aU(a))},vFa=function(a,b){if(3==a.C.Ra()){var c={RECEIVER_NAME:a.C.Bc("remote","currentReceiver").name};
c=g.X(b,128)?g.e0("$RECEIVER_NAME\uc5d0\uc11c \uc624\ub958 \ubc1c\uc0dd",c):b.rb()||g.X(b,4)?g.e0("$RECEIVER_NAME\uc5d0\uc11c \uc7ac\uc0dd \uc911",c):g.e0("$RECEIVER_NAME\uc5d0 \uc5f0\uacb0\ub428",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},M8=function(a,b){g.CY.call(this,"\uc7ac\uc0dd\ud560 \ud654\uba74:",0,a,b);
this.B=a;this.I={};this.R(a,"onMdxReceiversChange",this.L);this.R(a,"presentingplayerstatechange",this.L);this.L()},N8=function(a){g.GU.call(this,a);
this.B={key:p6(),name:"\uc774 \ucef4\ud4e8\ud130"};this.D=null;this.F=[];this.K=this.A=null;this.H=[this.B];this.C=this.B;this.G=new g.ZP(64);this.I=0;if(!g.cN(g.Y(this.o))){a=this.o;var b=g.bI(a);b&&(b=b.Am())&&(b=new M8(a,b),g.N(this,b));b=new L8(a);g.N(this,b);g.wU(a,b.element,4)}},uFa=function(a,b,c){a.G=c;
a.o.V("presentingplayerstatechange",new g.iQ(c,b))},O8=function(a,b){if(b.key!=a.C.key)if(b.key==a.B.key)A8();
else{a.C=b;var c=a.o.getPlaylistId();var d=a.o.getVideoData(1);var e=d.videoId;if(c||e){var f=a.o.lg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Yb(l).videoId}else k=[e];f=a.o.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.mk,index:Math.max(a.o.bC(),0),currentTime:0==f?void 0:f};(d=cDa(d))&&(c.locationInfo=d);d=c}else d=null;s8("Connecting to: "+g.Jg(b));"cast-selector-receiver"==b.key?(u8(d||null),P7()?M7().setLaunchParams(d||null):
K7("setLaunchParams called before ready.")):!d&&D8()&&r8()==b.key?g.oG("yt-remote-connection-change",!0):(A8(),u8(d||null),d=q8().ue(),(d=r6(d,b.key))&&B8(d,1))}},KDa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},O6={"'":"\\'"},wFa={},iDa={fZ:"atp",J3:"ska",Y2:"que",j2:"mus",F3:"sus",o0:"dsp"};
k6.prototype.qo=function(){var a=new k6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var x6,t6="",B6=y6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",CDa=y6("loadCastFramework")||y6("loadCastApplicationFramework"),MEa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(E6,g.M);g.h=E6.prototype;g.h.SK=function(a){this.C=arguments;this.o=!1;this.Da?this.B=(0,g.H)()+this.yd:this.Da=g.Dg(this.D,this.yd)};
g.h.stop=function(){this.Da&&(g.Eg(this.Da),this.Da=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.X=function(){this.stop();E6.fa.X.call(this)};
g.h.TK=function(){this.B?(this.Da=g.Dg(this.D,this.B-(0,g.H)()),this.B=null):(this.Da=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};F6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
F6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=G6.prototype;g.h.Hi=null;g.h.Kf=!1;g.h.ll=null;g.h.gx=null;g.h.Rk=null;g.h.dk=null;g.h.Ah=null;g.h.bi=null;g.h.ij=null;g.h.Qc=null;g.h.wn=0;g.h.Lf=null;g.h.mr=null;g.h.Bh=null;g.h.dm=-1;g.h.cF=!0;g.h.si=!1;g.h.Ct=0;g.h.tq=null;var IDa={},J6={};g.h=G6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.jW=function(a){a=a.target;var b=this.tq;b&&3==g.zx(a)?b.Wl():this.sG(a)};
g.h.sG=function(a){try{if(a==this.Qc)a:{var b=g.zx(this.Qc),c=this.Qc.A,d=this.Qc.getStatus();if(g.Hd&&!g.tc(10)||g.Jd&&!g.sc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.pf&&!g.Dx(this.Qc))break a;this.si||4!=b||7==c||(8==c||0>=d?this.o.Df(3):this.o.Df(2));Q6(this);var e=this.Qc.getStatus();this.dm=e;var f=g.Dx(this.Qc);(this.Kf=200==e)?(4==b&&M6(this),this.D?(JDa(this,b,f),g.pf&&this.Kf&&3==b&&(this.Y.W(this.A,"tick",this.fW),this.A.start())):L6(this,f),this.Kf&&!this.si&&(4==b?this.o.bq(this):
(this.Kf=!1,I6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Bh=3,K6(13)):(this.Bh=0,K6(14)),M6(this),N6(this))}}catch(k){this.Qc&&g.Dx(this.Qc)}finally{}};
g.h.fW=function(){var a=g.zx(this.Qc),b=g.Dx(this.Qc);this.wn<b.length&&(Q6(this),JDa(this,a,b),this.Kf&&4!=a&&I6(this))};
g.h.rV=function(a){P6((0,g.A)(this.qV,this,a),0)};
g.h.qV=function(a){this.si||(Q6(this),L6(this,a),I6(this))};
g.h.kE=function(a){P6((0,g.A)(this.pV,this,a),0)};
g.h.pV=function(a){this.si||(M6(this),this.Kf=a,this.o.bq(this),this.o.Df(4))};
g.h.cancel=function(){this.si=!0;M6(this)};
g.h.IV=function(){this.ll=null;var a=(0,g.H)();0<=a-this.gx?(2!=this.dk&&this.o.Df(3),M6(this),this.Bh=2,K6(18),N6(this)):MDa(this,this.gx-a)};g.h=PDa.prototype;g.h.At=null;g.h.Ce=null;g.h.uq=!1;g.h.qA=null;g.h.Fo=null;g.h.vu=null;g.h.Bt=null;g.h.We=null;g.h.Kg=-1;g.h.Zl=null;g.h.wl=null;g.h.connect=function(a){this.Bt=a;a=S6(this.o,null,this.Bt);K6(3);this.qA=(0,g.H)();var b=this.o.H;null!=b?(this.Zl=b[0],(this.wl=b[1])?(this.We=1,QDa(this)):(this.We=2,U6(this))):(j6(a,"MODE","init"),this.Ce=new G6(this,void 0,void 0,void 0),this.Ce.Hi=this.At,H6(this.Ce,a,!1,null,!0),this.We=0)};
g.h.YJ=function(a){if(a)this.We=2,U6(this);else{K6(4);var b=this.o;b.Yf=b.nh.Kg;a7(b,9)}a&&this.Df(2)};
g.h.Is=function(a){return this.o.Is(a)};
g.h.abort=function(){this.Ce&&(this.Ce.cancel(),this.Ce=null);this.Kg=-1};
g.h.pA=function(){return!1};
g.h.cE=function(a,b){this.Kg=a.dm;if(0==this.We)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Yf=this.Kg;a7(c,2);return}this.Zl=c[0];this.wl=c[1]}else c=this.o,c.Yf=this.Kg,a7(c,2);else if(2==this.We)if(this.uq)K6(7),this.vu=(0,g.H)();else if("11111"==b){if(K6(6),this.uq=!0,this.Fo=(0,g.H)(),c=this.Fo-this.qA,!g.Hd||g.tc(10)||500>c)this.Kg=200,this.Ce.cancel(),K6(12),T6(this.o,this,!0)}else K6(8),this.Fo=this.vu=(0,g.H)(),this.uq=!1};
g.h.bq=function(){this.Kg=this.Ce.dm;if(this.Ce.Kf)0==this.We?this.wl?(this.We=1,QDa(this)):(this.We=2,U6(this)):2==this.We&&((!g.Hd||g.tc(10)?!this.uq:200>this.vu-this.Fo)?(K6(11),T6(this.o,this,!1)):(K6(12),T6(this.o,this,!0)));else{0==this.We?K6(9):2==this.We&&K6(10);var a=this.o;a.Yf=this.Kg;a7(a,2)}};
g.h.kn=function(){return this.o.kn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Df=function(a){this.o.Df(a)};g.h=V6.prototype;g.h.Jl=null;g.h.ee=null;g.h.xc=null;g.h.zt=null;g.h.Jo=null;g.h.Ly=null;g.h.Wo=null;g.h.Sm=0;g.h.fR=0;g.h.xd=null;g.h.sh=null;g.h.yg=null;g.h.xi=null;g.h.nh=null;g.h.kr=null;g.h.sk=-1;g.h.oB=-1;g.h.Yf=-1;g.h.Sj=0;g.h.Fj=0;g.h.wi=8;var b7=new g.Of;g.B(SDa,g.nf);g.B(TDa,g.nf);g.B(UDa,g.nf);g.h=V6.prototype;g.h.connect=function(a,b,c,d,e){K6(0);this.zt=b;this.Jl=c||{};d&&g.u(e)&&(this.Jl.OSID=d,this.Jl.OAID=e);this.F?(P6((0,g.A)(this.gz,this,a),100),YDa(this)):this.gz(a)};
g.h.gz=function(a){this.nh=new PDa(this);this.nh.At=null;this.nh.A=this.D;this.nh.connect(a)};
g.h.pA=function(){return 0==this.o};
g.h.iE=function(a){this.sh=null;aEa(this,a)};
g.h.hE=function(){this.yg=null;this.xc=new G6(this,this.B,"rpc",this.G);this.xc.Hi=null;this.xc.Ct=0;var a=this.Ly.clone();g.Tm(a,"RID","rpc");g.Tm(a,"SID",this.B);g.Tm(a,"CI",this.kr?"0":"1");g.Tm(a,"AID",this.sk);W6(this,a);if(!g.Hd||g.tc(10))g.Tm(a,"TYPE","xmlhttp"),H6(this.xc,a,!0,this.Wo,!1);else{g.Tm(a,"TYPE","html");var b=this.xc,c=!!this.Wo;b.dk=3;b.Ah=i6(a.clone());LDa(b,c)}};
g.h.cE=function(a,b){if(0!=this.o&&(this.xc==a||this.ee==a))if(this.Yf=a.dm,this.ee==a&&3==this.o)if(7<this.wi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.yg){if(this.xc)if(this.xc.Rk+3E3<this.ee.Rk)Y6(this),this.xc.cancel(),this.xc=null;else break a;$6(this);K6(19)}}else this.oB=c[1],0<this.oB-this.sk&&37500>c[2]&&this.kr&&0==this.Fj&&!this.xi&&(this.xi=P6((0,g.A)(this.IR,this),6E3));else a7(this,11)}else b!=wFa.i_.o&&a7(this,11);else if(this.xc==a&&
Y6(this),!g.E(b)){c=this.D.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.sk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.Wo=e[2],e=e[3],null!=e?this.wi=e:this.wi=6,this.o=3,this.xd&&this.xd.Xy(),this.Ly=S6(this,this.kn()?this.Wo:null,this.zt),bEa(this)):"stop"==e[0]&&a7(this,7):3==this.o&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.xd&&this.xd.Wy(e),this.Fj=0)}}};
g.h.IR=function(){null!=this.xi&&(this.xi=null,this.xc.cancel(),this.xc=null,$6(this),K6(20))};
g.h.bq=function(a){if(this.xc==a){Y6(this);this.xc=null;var b=2}else if(this.ee==a)this.ee=null,b=1;else return;this.Yf=a.dm;if(0!=this.o)if(a.Kf)1==b?(b=(0,g.H)()-a.Rk,b7.dispatchEvent(new TDa(b7,a.ij?a.ij.length:0,b,this.Sj)),X6(this),this.C.length=0):bEa(this);else{var c=a.Bh,d;if(!(d=3==c||7==c||0==c&&0<this.Yf)){if(d=1==b)this.ee||this.sh||1==this.o||2<=this.Sj?d=!1:(this.sh=P6((0,g.A)(this.iE,this,a),cEa(this,this.Sj)),this.Sj++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,5);
break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.h.uK=function(a){if(!g.Oa(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.bX=function(a){a?K6(2):(K6(1),dEa(this,8))};
g.h.Is=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.tx;a.H=!1;return a};
g.h.isActive=function(){return!!this.xd&&this.xd.isActive(this)};
g.h.Df=function(a){b7.dispatchEvent(new UDa(b7,a))};
g.h.kn=function(){return!(!g.Hd||g.tc(10))};
g.h=eEa.prototype;g.h.Xy=function(){};
g.h.Wy=function(){};
g.h.Vy=function(){};
g.h.us=function(){};
g.h.Vz=function(){return{}};
g.h.isActive=function(){return!0};g.B(c7,g.M);g.h=c7.prototype;g.h.iV=function(){this.yd=Math.min(3E5,2*this.yd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.yd+15E3*Math.random();g.qu(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.yd=5E3};g.B(d7,eEa);g.h=d7.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.Xd=function(a){return this.B.Xd(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.lf(this.B),hEa(this),g.lf(this.A),this.A=null)};
g.h.la=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.I="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.o;e&&(e.xd=null);d.xd=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.sk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.gc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):e7(this)&&ZDa(this.o,c)};
g.h.Xy=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)ZDa(this.o,a[b])}this.V("handlerOpened")};
g.h.Vy=function(a){var b=2==a&&401==this.o.Yf;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.us=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.Vz=function(){var a={v:2};this.I&&(a.gsessionid=this.I);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.gc(a,this.D);return a};
g.h.Wy=function(a){"S"==a[0]?this.I=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),XDa(this.o)):this.V("handlerMessage",new fEa(a[0],a[1]))};
g.h.LX=function(){this.A.isActive();var a=this.o,b=0;a.xc&&b++;a.ee&&b++;0!=b||this.connect(this.D,this.C)};f7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
f7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
f7.prototype.D=function(a){a(Error("request timed out"))};var pEa=(0,g.H)(),i7=null,l7=Array(50),k7=-1,m7=!1;g.B(n7,g.ZF);n7.prototype.ue=function(){return this.o};
n7.prototype.contains=function(a){return!!q6(this.o,a)};
n7.prototype.get=function(a){return a?r6(this.o,a):null};
n7.prototype.info=function(a){j7(this.G,a)};g.B(o7,g.ZF);var xFa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=o7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Da)&&this.xG()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Da)||(g.pE(this.Da),this.Da=window.NaN)};
g.h.X=function(){this.stop();o7.fa.X.call(this)};
g.h.xG=function(){this.Da=window.NaN;this.o=g.EE(g7(this.F,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.A)(this.NX,this),onError:(0,g.A)(this.MX,this),Cd:(0,g.A)(this.OX,this)})};
g.h.NX=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new l6(c))};
g.h.MX=function(a){this.o=null;a.status&&404==a.status?this.A>=xFa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=xFa[this.A],this.Da=g.nE((0,g.A)(this.xG,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.OX=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.B(q7,n7);g.h=q7.prototype;g.h.start=function(){p7(this)&&this.V("screenChange");!g.kH("yt-remote-lounge-token-expiration")&&tEa(this);g.pE(this.A);this.A=g.nE((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){p7(this);qEa(this,a);r7(this,!1);this.V("screenChange");b(a);a.token||tEa(this)};
g.h.remove=function(a,b){var c=p7(this);sEa(this,a)&&(r7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.dr=function(a,b,c,d){var e=p7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,r7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.X=function(){g.pE(this.A);q7.fa.X.call(this)};
g.h.gL=function(a){p7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}r7(this,!b);b&&j7(this.G,"Missed "+b+" lounge tokens.")};
g.h.fL=function(a){j7(this.G,"Requesting lounge tokens failed: "+a)};g.B(t7,g.ZF);g.h=t7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.kH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.H)()-144E5<a?0:a)?v7(this):(this.C=(0,g.H)()+3E5,g.jH("yt-remote-fast-check-period",this.C),this.mw())};
g.h.isEmpty=function(){return g.Zb(this.o)};
g.h.update=function(){s7("Updating availability on schedule.");var a=this.F(),b=g.Lb(this.o,function(b,d){return b&&!!r6(a,d)},this);
u7(this,b)};
g.h.X=function(){g.pE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);t7.fa.X.call(this)};
g.h.mw=function(){g.pE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=wEa(this);if(g.Ob(a)){var b=g7(this.D,"/pairing/get_screen_availability");this.A=h7(this.D,b,{lounge_token:g.Rb(a).join(",")},(0,g.A)(this.QU,this,a),(0,g.A)(this.PU,this))}else u7(this,{}),v7(this)};
g.h.QU=function(a,b){this.A=null;var c=g.Rb(wEa(this));if(g.gb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;u7(this,d);v7(this)}else this.gc("Changing Screen set during request."),this.mw()};
g.h.PU=function(a){this.gc("Screen availability failed: "+a);this.A=null;v7(this)};
g.h.gc=function(a){j7("OnlineScreenService",a)};g.B(w7,n7);g.h=w7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.dr=function(a,b,c,d){this.B.contains(a)?this.B.dr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,j7(this.G,a),d(Error(a)))};
g.h.ue=function(a){return a?this.o:g.Wa(this.o,(0,g.Ud)(this.C,function(a){return!this.contains(a)},this))};
g.h.yG=function(){return(0,g.Ud)(this.ue(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.zG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new o7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.lf(f);d(x7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.lf(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.QX=function(a,b,c,d){g.EE(g7(this.F,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new l6(d.screen||{});if(!e.name||AEa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);AEa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(x7(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Cd:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.lf(this.B);g.lf(this.A);w7.fa.X.call(this)};
g.h.uL=function(){BEa(this);this.V("screenChange");this.A.update()};
w7.prototype.dispose=w7.prototype.dispose;g.B(z7,g.ZF);g.h=z7.prototype;g.h.cq=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.Be=function(a){this.la()||(a&&A7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){j7(this.M,a)};
g.h.BG=function(){return null};
g.h.uw=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){A7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.uw("");z7.fa.X.call(this)};g.B(B7,z7);g.h=B7.prototype;g.h.tw=function(a){if(this.o){if(this.o==a)return;A7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);DEa(this)};
g.h.uk=function(a){this.info("launchWithParams no-op for Cast: "+g.Jg(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.A)(function(){this.Be()},this),(0,g.A)(function(){this.Be(Error("Failed to stop receiver app."))},this)):this.Be(Error("Stopping cast device witout session."))};
g.h.uw=g.z;g.h.X=function(){this.info("disposeInternal");g.pE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;B7.fa.X.call(this)};
g.h.UV=function(a,b){if(!this.la())if(b){var c=g.nx(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Jg(c));switch(d){case "mdxSessionStatus":CEa(this,c.screenId);break;default:A7(this,"Unknown youtube message: "+d)}}else A7(this,"Unable to parse message.")}else A7(this,"No data in message.")};
g.h.fA=function(a,b,c,d){zEa(this.I,this.A.label,a,this.A.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(A7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.nE((0,g.A)(this.fA,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.BG=function(){return this.o};
g.h.RX=function(a){this.la()||a||(A7(this,"Cast session died."),this.Be())};g.B(C7,z7);g.h=C7.prototype;g.h.tw=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.uk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.z;g.pE(this.F);this.C?this.C.stop((0,g.A)(this.Be,this,null),(0,g.A)(this.Be,this,"Failed to stop DIAL device.")):this.Be()};
g.h.X=function(){this.o();this.o=g.z;g.pE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;C7.fa.X.call(this)};
g.h.UX=function(a){this.la()||a||(A7(this,"DIAL session died."),this.o(),this.o=g.z,this.Be())};
g.h.hu=function(a){this.K=p6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,FEa(this));a(b);EEa(this)}else this.G=(0,g.A)(function(){g.pE(this.F);this.G=g.z;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,FEa(this));a(b);EEa(this)},this),this.F=g.nE((0,g.A)(function(){this.G()},this),100)};
g.h.JM=function(a,b,c){zEa(this.I,this.H.receiver.label,a,this.A.friendlyName,(0,g.A)(function(a){a&&a.token?(this.cq(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.hu(b,c)},this),(0,g.A)(function(a){A7(this,"Failed to get DIAL screen: "+a);
this.hu(b,c)},this))};g.B(D7,z7);D7.prototype.stop=function(){this.Be()};
D7.prototype.tw=g.z;D7.prototype.uk=function(){g.pE(this.o);this.o=window.NaN;var a=r6(this.I.ue(),this.A.label);a?this.cq(a):this.Be(Error("No such screen"))};
D7.prototype.X=function(){g.pE(this.o);this.o=window.NaN;D7.fa.X.call(this)};g.B(E7,g.ZF);g.h=E7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.A)(this.eE,this),(0,g.A)(this.zU,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.sS,this);window.chrome.cast.initialize(c,
(0,g.A)(function(){this.la()||(window.chrome.cast.addReceiverActionListener(this.C),mEa(),this.A.subscribe("onlineScreenChange",(0,g.A)(this.AG,this)),this.B=HEa(this),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(a){this.gc("Failed to set initial custom receivers: "+g.Jg(a))},this)),this.V("yt-remote-cast2-availability-change",G7(this)),b(!0))},this),(0,g.A)(function(a){this.gc("Failed to initialize API: "+g.Jg(a));
b(!1)},this))};
g.h.JW=function(a,b){F7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)F7("Unsetting old screen status: "+this.o.A.friendlyName),H7(this,null)}if(a&&b){if(!this.o){c=r6(this.A.ue(),a);if(!c){F7("setConnectedScreenStatus: Unknown screen.");return}var d=GEa(this,c);d||(F7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(a){this.gc("Failed to set initial custom receivers: "+g.Jg(a))},this)));
F7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);H7(this,new D7(this.A,d),!0)}this.o.uw(b)}else F7("setConnectedScreenStatus: no screen.")};
g.h.KW=function(a){this.la()?this.gc("Setting connection data on disposed cast v2"):this.o?this.o.uk(a):this.gc("Setting connection data without a session")};
g.h.TX=function(){this.la()?this.gc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),H7(this,null)):F7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.A)(this.eE,this),(0,g.A)(this.UU,this))};
g.h.X=function(){this.A.unsubscribe("onlineScreenChange",(0,g.A)(this.AG,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Ta(g.y("yt.mdx.remote.debug.handlers_")||[],jEa);g.lf(this.o);E7.fa.X.call(this)};
g.h.gc=function(a){j7("Controller",a)};
g.h.fE=function(a,b){this.o==a&&(b||H7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.vU=function(a,b){if(!this.la())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),F7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)F7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{F7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:H7(this,
new D7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:H7(this,new C7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:H7(this,new B7(this.A,a));break;default:this.gc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.gc("Stopping receiver w/o session: "+a.friendlyName)}else this.gc("onReceiverAction_ called without receiver.")};
g.h.sS=function(a){if(this.la())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.gc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.gc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return F7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.gc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H7(this,new C7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.A)(b.JM,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.A)(b.hu,b))};
g.h.eE=function(a){if(!this.la()){F7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)F7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),H7(this,new B7(this.A,b),!0);else{this.gc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=r6(this.A.ue(),c.label);
d&&m6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(F7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.lf(this.o),this.o=new B7(this.A,b),this.o.subscribe("sessionScreen",(0,g.A)(this.fE,this,this.o)),this.o.uk(null));this.o.tw(a)}}};
g.h.SX=function(){return this.o?this.o.BG():null};
g.h.UU=function(a){this.la()||(this.gc("Failed to estabilish a session: "+g.Jg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&H7(this,null))};
g.h.zU=function(a){F7("Receiver availability updated: "+a);if(!this.la()){var b=G7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;G7(this)!=b&&this.V("yt-remote-cast2-availability-change",G7(this))}};
g.h.AG=function(){this.la()||(this.B=HEa(this),F7("Updating custom receivers: "+g.Jg(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(){this.gc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",G7(this)))};
E7.prototype.setLaunchParams=E7.prototype.KW;E7.prototype.setConnectedScreenStatus=E7.prototype.JW;E7.prototype.stopSession=E7.prototype.TX;E7.prototype.getCastSession=E7.prototype.SX;E7.prototype.requestSession=E7.prototype.requestSession;E7.prototype.init=E7.prototype.init;E7.prototype.dispose=E7.prototype.dispose;var N7=[];g.h=S7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";T7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.o=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.A=a.trackData,this.dg=a.hasPrevious,this.hasNext=a.hasNext,this.H=a.playerTime,this.G=a.playerTimeAt,this.D=a.seekableStart,this.B=a.seekableEnd,this.I=a.duration,this.K=a.loadedTime,this.C=a.liveIngestionTime,this.F=!(0,window.isNaN)(this.C))};
g.h.rb=function(){return 1==this.o};
g.h.isAdPlaying=function(){return 1081==this.o};
g.h.getDuration=function(){return this.F?this.I+U7(this):this.I};
g.h.clone=function(){return new S7(Y7(this))};g.B($7,g.ZF);g.h=$7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.z,f8(this,"play")):e8(this,"play"),d8(this,1,W7(a8(this))),this.V("remotePlayerChange")):b8(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.z,f8(this,"pause")):e8(this,"pause"),d8(this,2,W7(a8(this))),this.V("remotePlayerChange")):b8(this,this.pause)};
g.h.wG=function(a){if(1==this.o){if(this.A){var b=a8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.rb()||3==b.o?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.z,f8(this,"seekTo",{newTime:a}))}else e8(this,"seekTo",{newTime:a});d8(this,3,a);this.V("remotePlayerChange")}else b8(this,g.Fa(this.wG,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.z,f8(this,"stopVideo")):e8(this,"stopVideo");var a=a8(this);a.index=-1;a.videoId="";T7(a);c8(this,a);this.V("remotePlayerChange")}else b8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=a8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.A)(function(){j7("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.gc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.A)(function(){j7("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.gc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);e8(this,"setVolume",e)}c.muted=b;c.volume=a;c8(this,c)}else b8(this,g.Fa(this.setVolume,a,b))};
g.h.wF=function(a,b){if(1==this.o){var c=a8(this),d={videoId:a};b&&(c.A={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Jg(b.style),g.gc(d,c.A));e8(this,"setSubtitlesTrack",d);c8(this,c)}else b8(this,g.Fa(this.wF,a,b))};
g.h.mx=function(a,b){if(1==this.o){e8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Jb.id});var c=a8(this);c.audioTrackId=b.Jb.id;c8(this,c)}else b8(this,g.Fa(this.mx,a,b))};
g.h.vG=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"previous")}else b8(this,g.Fa(this.vG,a,b))};
g.h.uG=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"next")}else b8(this,g.Fa(this.uG,a,b))};
g.h.Az=function(){1==this.o?e8(this,"dismissAutoplay"):b8(this,this.Az)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}$7.fa.dispose.call(this)};
g.h.X=function(){UEa(this);this.C=null;this.D.clear();Z7(this,null);$7.fa.X.call(this)};
g.h.ox=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.GC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.qU=function(a,b){this.V(a,b)};
g.h.PR=function(a){if(!a)this.Vm(null),Z7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=a8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,c8(this,b)}};
g.h.Vm=function(a){j7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),VEa(this),this.V("remotePlayerChange")};
g.h.OR=function(a){a?(VEa(this),this.V("remotePlayerChange")):this.Vm(null)};
g.h.bS=function(){var a=REa();a&&Z7(this,a)};
g.h.gc=function(a){j7("CP",a)};g.B(g8,g.ZF);g.h=g8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.jb.listId=c);this.jb.videoId=d;this.jb.index=k||0;this.jb.state=3;V7(this.jb,m);this.C="UNSUPPORTED";h8("Connecting with setPlaylist and params: "+g.Jg(l));this.o.connect({method:"setPlaylist",
params:g.Jg(l)},a,qDa())}else h8("Connecting without params"),this.o.connect({},a,qDa());XEa(this)};
g.h.dispose=function(){this.la()||(this.V("beforeDispose"),i8(this,3));g8.fa.dispose.call(this)};
g.h.X=function(){j8(this);l8(this);k8(this);g.pE(this.I);this.I=window.NaN;g.pE(this.K);this.K=window.NaN;this.B=null;g.JF(this.T);this.T.length=0;this.o.dispose();g8.fa.X.call(this);this.C=this.G=this.A=this.jb=this.o=null};
g.h.XK=function(){this.F(2)};
g.h.TR=function(){h8("Channel opened");this.O&&(this.O=!1,k8(this),this.M=g.nE((0,g.A)(function(){h8("Timing out waiting for a screen.");this.F(1)},this),15E3));
uDa(gEa(this.o),this.aa)};
g.h.QR=function(){h8("Channel closed");(0,window.isNaN)(this.D)?w6(!0):w6();this.dispose()};
g.h.RR=function(a){w6();(0,window.isNaN)(this.H())?(h8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,h8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),i8(this,2))};
g.h.SR=function(a){a.params?h8("Received: action="+a.action+", params="+g.Jg(a.params)):h8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.nx(a.params.devices);this.A=(0,g.I)(a,function(a){return new k6(a)});
a=!!g.Ka(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
$Ea(this,a);break;case "loungeScreenDisconnected":g.Va(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
$Ea(this,!1);break;case "remoteConnected":var b=new k6(g.nx(a.params.device));g.Ka(this.A,function(a){return b?a.id==b.id:!1})||g.Ra(this.A,b);
break;case "remoteDisconnected":b=new k6(g.nx(a.params.device));g.Va(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":bFa(this,a);break;case "nowPlaying":dFa(this,a);break;case "onStateChange":cFa(this,a);break;case "onAdStateChange":eFa(this,a);break;case "onVolumeChanged":fFa(this,a);break;case "onSubtitlesTrackChanged":aFa(this,a);break;case "nowAutoplaying":gFa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":hFa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:h8("Unrecognized action: "+a.action)}};
g.h.uW=function(){if(this.B){var a=this.B;this.B=null;this.jb.videoId!=a&&m8(this,"getNowPlaying")}};
g8.prototype.subscribe=g8.prototype.subscribe;g8.prototype.unsubscribeByKey=g8.prototype.Xd;g8.prototype.ia=function(){var a=3;this.la()||(a=0,(0,window.isNaN)(this.H())?e7(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
g8.prototype.getProxyState=g8.prototype.ia;g8.prototype.F=function(a){h8("Disconnecting with "+a);j8(this);this.V("beforeDisconnect",a);1==a&&w6();hEa(this.o,a);this.dispose()};
g8.prototype.disconnect=g8.prototype.F;g8.prototype.ha=function(){var a=this.jb;this.B&&(a=this.jb.clone(),X7(a,this.B,a.index));return Y7(a)};
g8.prototype.getPlayerContextData=g8.prototype.ha;
g8.prototype.na=function(a){var b=new S7(a);b.videoId&&b.videoId!=this.jb.videoId&&(this.B=b.videoId,g.pE(this.I),this.I=g.nE((0,g.A)(this.uW,this),5E3));var c=[];this.jb.listId==b.listId&&this.jb.videoId==b.videoId&&this.jb.index==b.index||c.push("remoteQueueChange");this.jb.o==b.o&&this.jb.volume==b.volume&&this.jb.muted==b.muted&&W7(this.jb)==W7(b)&&g.Jg(this.jb.A)==g.Jg(b.A)||c.push("remotePlayerChange");this.jb.reset(a);(0,g.C)(c,function(a){this.V(a)},this)};
g8.prototype.setPlayerContextData=g8.prototype.na;g8.prototype.Z=function(){var a=this.o.F.id,b=g.Ka(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
g8.prototype.getOtherConnectedRemoteId=g8.prototype.Z;g8.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():window.NaN};
g8.prototype.getReconnectTimeout=g8.prototype.H;g8.prototype.ba=function(){return this.C||"UNSUPPORTED"};
g8.prototype.getAutoplayMode=g8.prototype.ba;g8.prototype.da=function(){return this.G||""};
g8.prototype.getAutoplayVideoId=g8.prototype.da;g8.prototype.wa=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.ru(a.o);a.start()}};
g8.prototype.reconnect=g8.prototype.wa;g8.prototype.ka=function(a,b){m8(this,a,b);ZEa(this)};
g8.prototype.sendMessage=g8.prototype.ka;g.B(n8,n7);g.h=n8.prototype;g.h.ue=function(a){return this.fd.$_gs(a)};
g.h.contains=function(a){return!!this.fd.$_c(a)};
g.h.get=function(a){return this.fd.$_g(a)};
g.h.start=function(){this.fd.$_st()};
g.h.add=function(a,b,c){this.fd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.fd.$_r(a,b,c)};
g.h.dr=function(a,b,c,d){this.fd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.A.length;a<b;++a)this.fd.$_ubk(this.A[a]);this.A.length=0;this.fd=null;n8.fa.X.call(this)};
g.h.PX=function(){this.V("screenChange")};
g.h.OT=function(){this.V("onlineScreenChange")};
w7.prototype.$_st=w7.prototype.start;w7.prototype.$_gspc=w7.prototype.QX;w7.prototype.$_gsppc=w7.prototype.zG;w7.prototype.$_c=w7.prototype.contains;w7.prototype.$_g=w7.prototype.get;w7.prototype.$_a=w7.prototype.add;w7.prototype.$_un=w7.prototype.dr;w7.prototype.$_r=w7.prototype.remove;w7.prototype.$_gs=w7.prototype.ue;w7.prototype.$_gos=w7.prototype.yG;w7.prototype.$_s=w7.prototype.subscribe;w7.prototype.$_ubk=w7.prototype.Xd;var o8=null,p8=null,E8=null,t8=[];g.t(F8,g.M);g.h=F8.prototype;
g.h.X=function(){g.M.prototype.X.call(this);this.C.stop();this.D.stop();this.L.stop();this.O();this.o.unsubscribe("proxyStateChange",this.bE,this);this.o.unsubscribe("remotePlayerChange",this.Ym,this);this.o.unsubscribe("remoteQueueChange",this.eq,this);this.o.unsubscribe("autoplayUpNext",this.xD,this);this.o.unsubscribe("previousNextChange",this.YD,this);this.o.unsubscribe("nowAutoplaying",this.PD,this);this.o.unsubscribe("autoplayDismissed",this.wD,this);this.o=this.H=null};
g.h.vC=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(I8(this)){if(!a8(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":a8(this.o).rb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.Wl(c[0],c[1]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":c=c[0],I8(this)&&this.o.mx(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();K8(this,0==c?void 0:c);break;case "control_seek":K8(this,c[0]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":c=c[0],I8(this)&&this.o.mx(this.A.getVideoData(1).videoId,c)}};
g.h.NR=function(a){this.L.SK(a)};
g.h.qX=function(a){this.vC("control_subtitles_set_track",g.Zb(a)?null:a)};
g.h.LF=function(){var a=this.A.Bc("captions","track");g.Zb(a)||J8(this,a)};
g.h.MD=function(a){if(I8(this)){this.o.unsubscribe("remotePlayerChange",this.Ym,this);var b=Math.round(a.volume);a=!!a.muted;var c=a8(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.M.start();this.o.subscribe("remotePlayerChange",this.Ym,this)}};
g.h.iT=function(){g.Zb(this.F)||tFa(this,this.F);this.G=!1};
g.h.bE=function(a,b){this.D.stop();2==b&&this.IF()};
g.h.Ym=function(){if(I8(this)){this.C.stop();var a=a8(this.o);switch(a.o){case 1081:case 1:H8(this,new g.ZP(8));this.HF();break;case 1085:case 3:H8(this,new g.ZP(9));break;case 1083:case 0:H8(this,new g.ZP(2));this.K.stop();G8(this,this.A.getVideoData().lengthSeconds);break;case 1084:H8(this,new g.ZP(4));break;case 2:H8(this,new g.ZP(4));G8(this,W7(a));break;case -1:H8(this,new g.ZP(64));break;case -1E3:H8(this,new g.ZP(128,{errorCode:"mdx.remoteerror",message:"\uc774 \ub3d9\uc601\uc0c1\uc740 \uc6d0\uaca9\uc73c\ub85c \uc7ac\uc0dd\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4."}))}a=
a8(this.o).A;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.F=a,tFa(this,a));a=a8(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.M.isActive()||this.hG()}else sFa(this)};
g.h.YD=function(){this.A.V("mdxpreviousnextchange")};
g.h.eq=function(){I8(this)||sFa(this)};
g.h.XJ=function(){this.o.Az()};
g.h.xD=function(a){a&&(a=g.EE("/watch_queue_ajax",{method:"GET",Xc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.uV,this)}))&&(this.O=(0,g.A)(a.abort,a))};
g.h.uV=function(a,b){var c=new g.MO(g.Y(this.A),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.V("mdxautoplayupnext",c)};
g.h.PD=function(a){(0,window.isNaN)(a)||this.A.V("mdxnowautoplaying",a)};
g.h.wD=function(){this.A.V("mdxautoplaycanceled")};
g.h.TP=function(a,b){-1==a8(this.o).o?K8(this,a):b&&this.o.wG(a)};
g.h.hG=function(){if(I8(this)){var a=a8(this.o);this.B.Ga(this.T);a.muted?this.A.mute():this.A.mg();this.A.setVolume(a.volume);this.T=this.B.R(this.A,"onVolumeChange",this.MD)}};
g.h.HF=function(){this.C.stop();if(!this.o.la()){var a=a8(this.o);a.rb()&&H8(this,new g.ZP(8));G8(this,W7(a));this.C.start()}};
g.h.IF=function(){this.D.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.D.start()};g.t(L8,g.W);L8.prototype.D=function(a){vFa(this,a.state)};g.t(M8,g.CY);M8.prototype.L=function(){var a=this.B.Bc("remote","receivers");a&&1<a.length&&!this.B.Bc("remote","quickCast")?(this.I=g.jb(a,this.F,this),g.DY(this,(0,g.I)(a,this.F)),a=this.B.Bc("remote","currentReceiver"),this.Cf(this.F(a)),this.enable(!0)):this.enable(!1)};
M8.prototype.F=function(a){return a.key};
M8.prototype.Bf=function(a){return"cast-selector-receiver"==a?"\uc804\uc1a1...":this.I[a].name};
M8.prototype.Ad=function(a){g.CY.prototype.Ad.call(this,a);this.B.Rd("remote","currentReceiver",this.I[a]);this.D.Ob()};g.t(N8,g.GU);g.h=N8.prototype;g.h.create=function(){mFa(g.PM(g.Y(this.o)));this.F.push(g.kG("yt-remote-before-disconnect",this.JR,this));this.F.push(g.kG("yt-remote-connection-change",this.AU,this));this.F.push(g.kG("yt-remote-receiver-availability-change",this.ZD,this));this.F.push(g.kG("yt-remote-auto-connect",this.yU,this));this.F.push(g.kG("yt-remote-receiver-resumed",this.xU,this));this.ZD()};
g.h.load=function(){this.o.av();g.GU.prototype.load.call(this);this.D=new F8(this,this.o,this.A);var a=(a=rFa())?a.currentTime:0;var b=D8()?new $7(y8(),void 0):null;0==a&&b&&(a=W7(a8(b)));0!=a&&(this.I=a||0,this.o.V("progresssync",a,void 0));uFa(this,this.G,this.G);g.M_(this.o.app,6)};
g.h.unload=function(){this.o.V("mdxautoplaycanceled");this.C=this.B;g.mf(this.D,this.A);this.A=this.D=null;g.GU.prototype.unload.call(this);g.M_(this.o.app,5)};
g.h.X=function(){g.lG(this.F);g.GU.prototype.X.call(this)};
g.h.Lm=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.D.vC.apply(this.D,[a].concat(g.oa(c)))};
g.h.NK=function(){return this.loaded?this.D.suggestion:null};
g.h.dg=function(){return this.A?a8(this.A).dg:!1};
g.h.hasNext=function(){return this.A?a8(this.A).hasNext:!1};
g.h.getCurrentTime=function(){return this.I};
g.h.HP=function(){var a=a8(this.A),b=this.o.getVideoData();return{allowSeeking:this.o.hd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+U7(a):a.C,isPeggedToLive:1>=(a.F?a.B+U7(a):a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+U7(a):a.B,seekableStart:0<a.D?a.D+U7(a):a.D}};
g.h.IP=function(){this.A&&this.A.uG()};
g.h.JP=function(){this.A&&this.A.vG()};
g.h.JR=function(a){1==a&&(this.K=this.A?a8(this.A):null)};
g.h.AU=function(){var a=D8()?new $7(y8(),void 0):null;if(a){var b=this.C;this.loaded&&this.unload();this.A=a;this.K=null;b.key!=this.B.key&&(this.C=b,this.load())}else g.lf(this.A),this.A=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.o.getVideoData().videoId&&this.o.ZB(a.videoId,W7(a)));this.o.V("videodatachange","newdata",this.o.getVideoData(),3)};
g.h.ZD=function(){this.H=[this.B].concat(oFa());var a=z8()||this.B;O8(this,a);this.o.xa("onMdxReceiversChange")};
g.h.yU=function(){var a=z8();O8(this,a)};
g.h.xU=function(){this.C=z8()};
g.h.GP=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?Q7():O8(this,b)),this.loaded?this.C:this.B;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&Q7(),!0):!1}};
g.h.KP=function(){e8(this.A,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Jc=function(){return!1};g.CX.remote=N8;})(_yt_player);
